/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupabaseTestRouteImport } from './routes/supabase-test'
import { Route as RlsTestRouteImport } from './routes/rls-test'
import { Route as HealthRouteImport } from './routes/health'
import { Route as DbTestRouteImport } from './routes/db-test'
import { Route as AnonTestRouteImport } from './routes/anon-test'
import { Route as IndexRouteImport } from './routes/index'

const SupabaseTestRoute = SupabaseTestRouteImport.update({
  id: '/supabase-test',
  path: '/supabase-test',
  getParentRoute: () => rootRouteImport,
} as any)
const RlsTestRoute = RlsTestRouteImport.update({
  id: '/rls-test',
  path: '/rls-test',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DbTestRoute = DbTestRouteImport.update({
  id: '/db-test',
  path: '/db-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AnonTestRoute = AnonTestRouteImport.update({
  id: '/anon-test',
  path: '/anon-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anon-test': typeof AnonTestRoute
  '/db-test': typeof DbTestRoute
  '/health': typeof HealthRoute
  '/rls-test': typeof RlsTestRoute
  '/supabase-test': typeof SupabaseTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anon-test': typeof AnonTestRoute
  '/db-test': typeof DbTestRoute
  '/health': typeof HealthRoute
  '/rls-test': typeof RlsTestRoute
  '/supabase-test': typeof SupabaseTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anon-test': typeof AnonTestRoute
  '/db-test': typeof DbTestRoute
  '/health': typeof HealthRoute
  '/rls-test': typeof RlsTestRoute
  '/supabase-test': typeof SupabaseTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anon-test'
    | '/db-test'
    | '/health'
    | '/rls-test'
    | '/supabase-test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anon-test'
    | '/db-test'
    | '/health'
    | '/rls-test'
    | '/supabase-test'
  id:
    | '__root__'
    | '/'
    | '/anon-test'
    | '/db-test'
    | '/health'
    | '/rls-test'
    | '/supabase-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnonTestRoute: typeof AnonTestRoute
  DbTestRoute: typeof DbTestRoute
  HealthRoute: typeof HealthRoute
  RlsTestRoute: typeof RlsTestRoute
  SupabaseTestRoute: typeof SupabaseTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supabase-test': {
      id: '/supabase-test'
      path: '/supabase-test'
      fullPath: '/supabase-test'
      preLoaderRoute: typeof SupabaseTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rls-test': {
      id: '/rls-test'
      path: '/rls-test'
      fullPath: '/rls-test'
      preLoaderRoute: typeof RlsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db-test': {
      id: '/db-test'
      path: '/db-test'
      fullPath: '/db-test'
      preLoaderRoute: typeof DbTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anon-test': {
      id: '/anon-test'
      path: '/anon-test'
      fullPath: '/anon-test'
      preLoaderRoute: typeof AnonTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnonTestRoute: AnonTestRoute,
  DbTestRoute: DbTestRoute,
  HealthRoute: HealthRoute,
  RlsTestRoute: RlsTestRoute,
  SupabaseTestRoute: SupabaseTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
